import {FIELDS} from './macro-config.js?v=2.18';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=x=>Number.isFinite(x)?x.toFixed(2):'未取得';
const delta=x=>`${x>0?'+':''}${n(x)}`;
export function regimePanel(r,c){
 const color={gray:'#64748b',yellow:'#b77900',red:'#c53030'}[r.color];
 const label={gray:'灰：判定保留',yellow:'黄：警戒',red:'赤：ストレス警戒'}[r.color];
 return `<div class="macro-card" id="macroRegime" style="border-left:5px solid ${color}"><b>${label}</b><h3>${esc(r.label)}</h3><p>${esc(r.reason)}</p><p>${esc(r.actions)}</p><small>未校正の暫定評価です。買い増し・ナンピン・売却はご自身の裁量。個別戦略の抽出や理想配分は変更しません。</small><p>次の確認・変更条件：${esc(r.next)}</p><details><summary>根拠・不足データ</summary><p>${esc(r.coverage)}。充足率は的中確率ではありません。</p>${r.signals.map(x=>`<p>・${esc(x)}</p>`).join('')}${r.evidence.map(x=>`<p>${esc(x)}</p>`).join('')}<p>未取得・更新待ち：${r.missing.length?r.missing.map(esc).join('、'):'接続指標の個別比較値は取得済み'}</p><p>未接続：${r.gaps.map(esc).join('、')}。これらが未確認のため、自動で青にはしません。</p><p>指標の役割：土台＝金利・カーブ／脆弱性＝株高と信用の乖離（銀行株・需給は未接続）／ストレス＝HY・BBB・VIX。雇用は景気の補助確認。</p></details><details><summary>S1〜S6への影響と確認事項</summary>${r.strategies.map(s=>`<p><b>${esc(s.name)}</b><br>${esc(s.text)}</p>`).join('')}<p>新しい戦略分類の参考表示です。保存済みの銘柄・戦略IDを移行したものではありません。</p></details><details><summary>判定方法と変更可能な目安</summary><p>単純多数決ではなく、重大な信用ストレス→信用と他因子の悪化→個別の警戒材料の順に確認します。赤は下落の確定ではありません。</p><p>重大ストレス：同じ期間でHYが+${n(c.severeHy)}%pt以上、BBBが+${n(c.severeBbb)}%pt以上拡大、またはHY水準${n(c.crisisHy)}%以上かつ1週間で+${n(c.crisisWeek)}%pt以上拡大。他指標の欠損でも赤を表示します。</p><p>通常の赤：HY +${n(c.hy)}%pt、BBB +${n(c.bbb)}%ptの1か月同時拡大に、VIX +${n(c.vix)}ptの1か月上昇または失業率+${n(c.unemployment)}%ptの3か月上昇が重なる場合。その他の警戒材料は黄。材料が不足する場合は灰。</p><p>閾値は表示用の仮設定で、予測精度・収益性は未検証です。継続日数による判定固定は未実装です。</p></details><button type="button" class="chip" id="macroSettingsOpen">マクロ判定の設定</button></div>`;
}
export function formulaPanel(r){
 const v=r.rates?.values,cv=r.curve?.values;
 const formula=v?`${n(v.DGS10.value)}% ≈ ${n(v.DFII10.value)}% ＋ ${n(v.T10YIE.value)}%`:'同日の名目・実質・BEIが揃わないため、実測の分解は保留';
 const decomposition=v?`<p>共通観測日 ${esc(r.rates.to)}：<b>${formula}</b><br>${esc(r.rates.from)}からの変化：名目 ${delta(v.DGS10.change)}%pt ≈ 実質 ${delta(v.DFII10.change)}%pt ＋ BEI ${delta(v.T10YIE.change)}%pt</p><p>分解の残差：${n(v.DGS10.value-v.DFII10.value-v.T10YIE.value)}%pt。丸めや系列の更新差があり得るため、完全一致を前提にしません。成長期待と財政・タームプレミアムの原因識別は別の資料が必要です。</p>`:`<p>${formula}</p>`;
 return `<div class="macro-card" id="macroFormula"><h3>式で分かる：金利と株価</h3><p><b>名目金利 ≈ 実質金利 ＋ 期待インフレ率</b><br>物価調整前の金利を「物価を除いた部分」と「将来の物価上昇の見込み」に分ける考え方です。</p><p><b>実質金利 ≈ 名目金利 − 期待インフレ率</b><br>例：名目4.2% − 期待インフレ2.3% ≈ 実質1.9%。これは説明用の例で、現在値ではありません。</p><p>この画面では期待インフレの市場指標にBEIを使用します。BEIは純粋な予想だけでなく、リスクへの対価や流動性の影響を含みます。</p>${decomposition}<details><summary>長短金利差・信用スプレッド・EPSの式</summary><p><b>長短金利差 ＝ 10年金利 − 2年金利</b><br>負の値は逆イールド。金利差が増えた理由を両金利の動きで確認します。</p><p><b>社債利回り ≈ 国債利回り ＋ 信用スプレッド</b><br>例：国債4% ＋ 上乗せ3%pt ≈ 社債7%。概念例です。OASは年限・組み込みオプション等を調整するため、実際は単純差とは異なります。</p><p><b>株価 ＝ EPS × PER</b><br>1株利益×利益何倍の価格か。同じ基準のEPSを使います。予想EPSなら予想PERとの組み合わせです。</p><p><b>長期国債利回り ≈ 将来の短期金利の平均予想 ＋ タームプレミアム</b><br>タームプレミアムは長く保有する金利変動などの不確実性への対価。直接観測できず、推計モデルに依存します。</p><p>名目と実質の厳密な関係の基本形は（1＋名目）＝（1＋実質）×（1＋インフレ）。単純な足し算は低い率での近似です。TIPS・BEIはこの基本形に市場のリスク要因が加わります。</p></details></div>
 <div class="macro-card" id="macroCurve"><h3>金利カーブ：${esc(r.curveLabel)}</h3>${cv?`<p>${esc(r.curve.from)} → ${esc(r.curve.to)}<br>10年 ${delta(cv.DGS10.change)}%pt ／ 2年 ${delta(cv.DGS2.change)}%pt<br>長短差：${n(cv.DGS10.before-cv.DGS2.before)} → ${n(cv.DGS10.value-cv.DGS2.value)}%pt</p>`:'<p>同じ日付の金利が必要です。</p>'}<p>Bullは債券価格上昇＝金利低下、Bearは金利上昇。名称だけで株の良否を判定せず、信用・利益と組み合わせます。</p></div>
 <div class="macro-card" id="macroDivergence"><h3>株式と信用の方向</h3>${r.divergence?`<p>共通期間 ${esc(r.divergence.from)} → ${esc(r.divergence.to)}<br>S&P 500 ${delta(r.equity)}% ／ HY ${delta(r.divergence.values.BAMLH0A0HYM2.change)}%pt</p>`:'<p>共通期間のデータ不足で判定保留。</p>'}<p>株が上がる一方でHYが拡大していれば、株式と信用の見方のずれを点検。HYは必ず株より先行するわけではありません。</p></div>`;
}
export function settingsPanel(c){return `<dialog id="macroSettings" aria-labelledby="macroSettingsTitle" style="width:min(560px,100vw);max-height:90dvh;background:var(--sur);color:var(--ink);border:1px solid var(--line);border-radius:12px"><div style="position:sticky;top:0;background:var(--sur);display:flex;justify-content:space-between;padding:12px"><b id="macroSettingsTitle">マクロ判定の設定</b><button type="button" class="chip" id="macroSettingsClose">閉じる</button></div><p class="hint">この端末に保存。表示上の警戒目安を変更します。仮の初期値で、売買・理想配分に連動しません。</p><form id="macroSettingsForm">${FIELDS.map(([key,title,unit,min,max])=>`<label style="display:block;margin:12px">${esc(title)}（${esc(unit)}）<input style="display:block;width:100%;font-size:16px" name="${key}" type="number" step="any" min="${min}" max="${max}" value="${c[key]}" required></label>`).join('')}<button class="chip" type="submit">保存して再判定</button><button class="chip" type="button" id="macroSettingsReset">初期値に戻す</button></form><p id="macroSettingsStatus" role="status"></p></dialog>`;}
