'use strict';
const M=RRModel,$=id=>document.getElementById(id),key='risk-return-lab-v01';
const initial=()=>RRResearch().map(r=>RRWorkflowAttach(RRDecisionAttach(r,true)));
let records=initial(),selected=0,isDemo=false,realRecords=null;
function validRecord(r){return r&&(!r.workflow||RRWorkflowModel.valid(r.workflow))&&(!r.decision||RRDecisionModel.valid(r.decision))&&typeof r.code==='string'&&typeof r.name==='string'&&['asset','growth'].every(k=>Array.isArray(r[k])&&r[k].length===4&&r[k].every(x=>x===null||(Number.isInteger(x)&&x>=0&&x<=5)))&&Array.isArray(r.evidence)&&r.evidence.length===8&&r.evidence.every(e=>e&&['note','url','date','kind'].every(k=>typeof e[k]==='string')&&['unverified','primary','secondary','assumption'].includes(e.kind))&&['price','bear','base','bull'].every(k=>r[k]===null||(typeof r[k]==='number'&&Number.isFinite(r[k])&&r[k]>=0))&&['date','scenarioNote','reviewDate','breakCondition'].every(k=>typeof r[k]==='string')&&Number.isInteger(r.horizon)&&r.horizon>=1&&r.horizon<=36&&Array.isArray(r.history)&&r.history.length<=200;}
function parse(raw){const d=JSON.parse(raw);if(d.schema!==1||!Array.isArray(d.records)||d.records.length<1||d.records.length>100||!d.records.every(validRecord))throw Error('形式が一致しません');return d.records.map(r=>RRWorkflowAttach(RRDecisionAttach(r,true)));}
try{const s=localStorage.getItem(key);if(s)records=parse(s);}catch(e){$('status').textContent='保存記録を読めませんでした。初期状態で表示しています。';}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,s='')=>n===null?'保留':n.toFixed(1)+s;
function charts(){
 RRDecisionUI.refresh(records[selected]);
 RRWorkflowUI.refresh(records,records[selected],esc);
 $('thesisCompare').innerHTML='<table><thead><tr><th>銘柄</th><th>必要な条件</th><th>強い反論</th></tr></thead><tbody>'+records.map(r=>'<tr><td>'+esc(r.name)+'</td><td>'+esc(r.decision?.essential||'未記入')+'</td><td>'+esc(r.decision?.counter||'未記入')+'</td></tr>').join('')+'</tbody></table>';
 const data=records.map((r,i)=>({r,i,m:M.metrics(r)}));
 function draw(id,points,xMax,yMin,yMax,xLabel,yLabel){const svg=$(id),w=Math.max(270,svg.clientWidth),h=270,l=44,b=38,t=25,right=18,plotW=w-l-right,plotH=h-b-t;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);const x=v=>l+v/xMax*plotW,y=v=>h-b-(v-yMin)/(yMax-yMin)*plotH;let s=`<title>${esc(xLabel)}と${esc(yLabel)}</title>`;for(let i=0;i<=4;i++){const vx=xMax*i/4,vy=yMin+(yMax-yMin)*i/4;s+=`<path d="M${x(vx)} ${t}V${h-b} M${l} ${y(vy)}H${w-right}" stroke="var(--line)" fill="none"/><text x="${x(vx)}" y="${h-b+17}" text-anchor="middle">${Math.round(vx)}</text><text x="${l-7}" y="${y(vy)+4}" text-anchor="end">${Math.round(vy)}</text>`;}s+=`<text x="${l}" y="15">${esc(yLabel)}</text><text x="${w-right}" y="${h-2}" text-anchor="end">${esc(xLabel)}</text>`;for(const p of points){s+=`<circle cx="${x(p.x)}" cy="${y(p.y)}" r="${p.i===selected?7:5}" fill="var(--accent)" opacity="${p.i===selected?1:.55}"><title>${esc(p.r.name)}</title></circle><text x="${Math.min(w-right-3,Math.max(l+3,x(p.x)))}" y="${Math.max(t+12,y(p.y)-10)}" text-anchor="${p.x>xMax*.75?'end':'start'}">${esc(p.r.code)}</text>`;}if(!points.length)s+=`<text x="${w/2}" y="${h/2}" text-anchor="middle">入力待ち・架空例で操作できます</text>`;svg.innerHTML=s;}
 draw('quality',data.filter(d=>d.m.asset!==null&&d.m.growth!==null).map(d=>({...d,x:d.m.asset,y:d.m.growth})),100,0,100,'下支え（点）','成長（点）');
 const ps=data.filter(d=>d.m.valid).map(d=>({...d,x:d.m.down,y:d.m.up}));draw('payoff',ps,Math.max(30,...ps.map(p=>p.x))*1.15,Math.min(0,...ps.map(p=>p.y))-5,Math.max(40,...ps.map(p=>p.y))*1.15,'弱気時の下落（%）','基本シナリオ上昇（%）');
 $('compare').innerHTML=data.map(({r,m})=>`<tr><td>${esc(r.name)}</td><td>${m.asset??'保留'}</td><td>${m.growth??'保留'}</td><td>${m.coverage}%</td><td>${fmt(m.down,'%')}</td><td>${fmt(m.up,'%')}</td><td>${fmt(m.ratio,'倍')}</td></tr>`).join('');
 const m=data[selected].m;$('metrics').innerHTML=[['下支え',m.asset===null?'保留':m.asset+' / 100'],['成長',m.growth===null?'保留':m.growth+' / 100'],['根拠記入率',m.coverage+'%']].map(([a,b])=>`<div class="metric">${a}<span class="value">${b}</span></div>`).join('');
 $('scenarioResult').textContent=m.valid?`弱気 ${fmt(-m.down,'%')} ／ 基本 ${fmt(m.up,'%')} ／ 強気 ${fmt(m.bull,'%')}　上昇÷下落 ${fmt(m.ratio,'倍')}（実現確率を考慮しない比較）`:'価格を入力してください：0 ≦ 弱気 < 基準株価、弱気 ≦ 基本 ≦ 強気。';
}
function render(){const r=RRWorkflowAttach(RRDecisionAttach(records[selected]));RRDecisionUI.render(r,esc,charts);RRWorkflowUI.render(r,esc,charts);$('addCandidate').onclick=()=>{if(isDemo){$('status').textContent='実在銘柄の画面へ戻って追加してください。';return;}const code=$('newCode').value.trim().toUpperCase(),name=$('newName').value.trim();if(!/^[0-9A-Z]{4,5}$/.test(code)||!name||records.some(a=>a.code===code)||records.length>=100){$('status').textContent='コード・会社名・重複を確認してください（最大100社）。';return;}records.push(RRWorkflowAttach(RRDecisionAttach(M.blank(code,name))));selected=records.length-1;render();$('status').textContent='未評価の候補を追加しました。記録ボタンで保存します。';};$('company').innerHTML=records.map((v,i)=>`<option value="${i}">${esc(v.code)} ${esc(v.name)}</option>`).join('');$('company').value=selected;$('mode').textContent=isDemo?'架空データの操作例・実在銘柄の評価ではありません':(r.rubricVersion===RRRubric.version?'仮説・反証・感応度の検討用。9/26調査メモ／9/25価格。自動順位・上昇確率は算出しません。':'旧基準の記録：比較点は保留。元の編集は保持しています。');$('demo').textContent=isDemo?'実在銘柄の調査へ戻る':'架空例で操作を試す';$('detailTitle').textContent=r.name+' の根拠と評価';for(const k of ['date','horizon','price','bear','base','bull','scenarioNote','reviewDate','breakCondition'])$(k).value=r[k]??'';
 $('criteria').innerHTML=Object.entries(M.groups).map(([group,items],gi)=>`<div><h3>${gi?'利益成長':'資産・財務の下支え'}</h3>${items.map(([name,hint],i)=>{const n=gi*4+i,e=r.evidence[n];return `<div class="item"><label>${esc(RRRubric.names[n])}<select data-score="${group}:${i}"><option value="">未確認</option>${RRRubric.levels[n].map((a,j)=>`<option value="${j}" ${r[group][i]===j?'selected':''}>${j} · ${a}</option>`).join('')}</select></label><small>${hint}</small><label>根拠の区分<select data-e="${n}:kind">${[['unverified','未確認'],['primary','一次資料'],['secondary','二次資料'],['assumption','分析上の仮定']].map(([k,v])=>`<option value="${k}" ${e.kind===k?'selected':''}>${v}</option>`).join('')}</select></label><label>根拠・反対材料<textarea data-e="${n}:note">${esc(e.note)}</textarea></label><label>出典URL／資料識別子<input data-e="${n}:url" value="${esc(e.url)}"></label><label>資料日<input type="date" data-e="${n}:date" value="${esc(e.date)}"></label></div>`;}).join('')}</div>`).join('');
 $('history').innerHTML=r.history.slice(-5).reverse().map(h=>'<details><summary>'+esc(h.at)+' · '+esc(h.reason)+'</summary><p>当時の記録。現在の評価で書き換えていません。</p><pre class="snapshot">'+esc(JSON.stringify(h.snapshot||h.summary,null,2))+'</pre></details>').join('')||'<p class="muted">記録はまだありません。</p>';charts();}
 $('anchors').innerHTML='<p>基準 '+RRRubric.version+'。各項目の選択肢に0〜5点の条件を表示。条件を満たす最も高い点を採用し、不明なら保留。点は5点刻みで、5点差を優劣の確定としません。</p><p>調整換金資産比率＝（現預金＋有価証券×50%−総負債）÷時価総額。債権・在庫・固定資産を除く共通ストレス指標で、清原式や清算価値ではありません。掛目・境界・等配点の予測力は未検証。財務耐久力は自己資本比率を代理指標とし、未解決の重大な調達懸念があれば上限3点。</p><p>成長点は成長の証拠と期待差の強さ。成長率・株価上昇確率ではありません。資料日は公開日、公開日不明のWeb表は確認日。根拠区分は資料の種類で、採点自体は分析判断です。</p>';
 $('company').onchange=()=>{selected=Number($('company').value);render();};
 for(const k of ['date','horizon','price','bear','base','bull','scenarioNote','reviewDate','breakCondition'])$(k).oninput=()=>{records[selected][k]=['horizon','price','bear','base','bull'].includes(k)?($(k).value===''?null:Number($(k).value)):$(k).value;charts();};
 $('criteria').oninput=e=>{const r=records[selected];if(e.target.dataset.score){const[g,i]=e.target.dataset.score.split(':');r[g][i]=e.target.value===''?null:Number(e.target.value);}if(e.target.dataset.e){const[i,k]=e.target.dataset.e.split(':');r.evidence[i][k]=e.target.value;}charts();};
 $('demo').onclick=()=>{if(isDemo){records=realRecords;isDemo=false;}else{realRecords=records;records=['資産型A','成長型B','両立型C'].map((n,i)=>{const r=M.blank('DEMO'+i,n);Object.assign(r,{date:'2026-09-26',price:100,bear:[80,55,75][i],base:[125,160,145][i],bull:[140,200,175][i],asset:[[5,4,4,3],[2,3,2,3],[4,4,4,4]][i],growth:[[2,2,3,1],[5,4,4,5],[4,3,4,4]][i],scenarioNote:'仕組みを説明する架空の仮定。実在企業の予想ではありません。'});r.evidence=r.evidence.map(()=>({kind:'assumption',note:'操作説明のための架空評価',url:'DEMO',date:'2026-09-26'}));return r;});isDemo=true;}selected=0;render();};
 $('save').onclick=()=>{const r=records[selected];if(!validRecord(r)){ $('status').textContent='入力を確認してください（期間は1〜36か月など）。';return;}if(r.history.length>=200){$('status').textContent='記録上限200件です。書き出して保管してください。';return;}const snapshot=JSON.parse(JSON.stringify({...r,history:undefined}));r.history.push({at:new Date().toISOString(),reason:$('reason').value,summary:M.metrics(r),snapshot});try{if(!isDemo)localStorage.setItem(key,JSON.stringify({schema:1,records}));$('status').textContent=isDemo?'架空例の一時記録です。実在銘柄の保存には混ぜません。':'このブラウザーに記録しました。';}catch(e){r.history.pop();$('status').textContent='保存できませんでした。書き出しで記録を保管してください。';}render();};
 $('export').onclick=()=>{const blob=new Blob([JSON.stringify({schema:1,demo:isDemo,records},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=isDemo?'risk-return-demo.json':'risk-return-research.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 $('import').onchange=async()=>{try{const f=$('import').files[0];if(!f)return;if(f.size>2000000)throw Error('2MB以下にしてください');const raw=await f.text(),d=JSON.parse(raw),incoming=parse(raw);if(d.demo){$('status').textContent='架空例は実在銘柄の記録へ読み込めません。';return;}if(!confirm('画面上の調査記録を読み込みデータに置き換えます。未保存の編集は失われます。'))return;records=incoming;selected=0;isDemo=false;realRecords=null;render();$('status').textContent='読み込みました。「現在の評価を記録」でブラウザーに保存します。';}catch(e){$('status').textContent='読み込み失敗：'+e.message;}finally{$('import').value='';}};
new ResizeObserver(charts).observe($('quality'));render();

$('research').onclick=()=>{if(!confirm('現在の画面を9/26調査版へ置き換えます。編集済み記録は先に書き出してください。保存するまで既存のブラウザー記録は保持されます。'))return;records=initial();selected=0;isDemo=false;realRecords=null;render();$('status').textContent='調査版を読み込みました。保存するには「現在の評価を記録」を押してください。';};

for(const id of ['price','date'])$(id).addEventListener('input',()=>{records[selected].asset[0]=null;const el=document.querySelector('[data-score="asset:0"]');if(el)el.value='';$('status').textContent='株価・基準日を変更したため換金資産比率の点を保留しました。新しい時価総額で再計算して採点してください。';charts();});
