'use strict';
(function(){
 const main=document.querySelector('main'),advanced=document.createElement('details'),sources=document.createElement('details'),home=document.createElement('section');
 advanced.id='manualResearch';advanced.innerHTML='<summary>詳細を確認・修正する（任意・変更は自動保存）</summary><p>これまでの手動分析を保持しています。普段はこちらの入力は不要です。公開調査の分析案とは別に、ご自身の見立てを記録できます。</p>';
 [...main.children].filter(n=>n.id!=='researchFeed').forEach(n=>advanced.append(n));
 sources.id='sourceResearch';sources.innerHTML='<summary>開示一覧・出典・8項目の調査メモを詳しく見る</summary>';const feed=document.querySelector('#researchFeed');if(feed)sources.append(feed);
 home.id='autoResearch';main.append(home,sources,advanced);
 const storageKey='research-personal-v1';let personal={version:1,cash:null,assets:null,lossBudget:null,maxWeight:null,returnRequired:null,holdings:[],decisions:[]},saveError='';
 try{const raw=localStorage.getItem(storageKey);if(raw){const p=JSON.parse(raw);if(!validPersonal(p))throw Error();personal=p;}}catch{saveError='個人設定を読めませんでした。元の保存内容は上書きせず、バックアップを確認してください。';}
 function validPersonal(p){return p&&p.version===1&&['cash','assets','lossBudget','maxWeight','returnRequired'].every(k=>p[k]===null||(typeof p[k]==='number'&&Number.isFinite(p[k])&&p[k]>=0&&(k!=='maxWeight'||p[k]<=100)))&&Array.isArray(p.holdings)&&p.holdings.length<=100&&p.holdings.every(h=>h&&/^[0-9A-Z]{4}$/.test(h.code)&&typeof h.name==='string')&&Array.isArray(p.decisions)&&p.decisions.length<=500&&p.decisions.every(d=>d&&/^[0-9A-Z]{4}$/.test(d.code)&&['購入を検討','待つ','見送る'].includes(d.choice)&&typeof d.at==='string'&&typeof d.researchAsOf==='string');}
 const finite=n=>typeof n==='number'&&Number.isFinite(n),num=n=>finite(n)?n.toLocaleString('ja-JP',{maximumFractionDigits:2}):'未確認';
 const link=(url,label)=>{try{const u=new URL(url);if(u.protocol==='https:')return `<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`;}catch{}return esc(label);};
 let data=null;
 function save(){try{if(!validPersonal(personal))throw Error('入力値を確認してください');localStorage.setItem(storageKey,JSON.stringify(personal));saveError='';document.querySelector('#personalSaved').textContent='この端末に自動保存しました。';return true;}catch{saveError='保存できません。入力値・保存領域を確認し、必要ならバックアップしてください。';document.querySelector('#personalSaved').textContent=saveError;return false;}}
 function sizing(c){const q=c.quote,s=c.scenario;if(!c.scenarioUsable||!s||!finite(q.price)||q.price<=0)return null;const prices=s.cases.map(x=>x.eps*x.per),down=(q.price-prices[0])/q.price;if(!(down>0&&down<=1))return null;const p=personal;if(![p.cash,p.assets,p.lossBudget,p.maxWeight,p.returnRequired].every(x=>finite(x)&&x>0))return null;return{limit:Math.min(p.cash,p.lossBudget/down,p.assets*p.maxWeight/100),entry:prices[1]/(1+p.returnRequired/100),down};}
 function cards(){const area=document.querySelector('#autoCards');if(!area)return;const auto=data?.report?.autopilot;area.innerHTML=auto?auto.cards.map(c=>{const m=c.memo,q=c.quote,s=c.scenario,amount=sizing(c),last=personal.decisions.filter(d=>d.code===c.code).at(-1);return `<article class="auto-card"><h3>${esc(c.code+' '+m.name)}</h3><p class="auto-verdict">${esc(m.verdict)}</p><p>${finite(q.price)?num(q.price)+'円':'株価未取得'} · ${esc(q.date||'日付不明')}終値 ／ ${esc(q.status)} ${link(q.source,'価格出典')}</p><small>${esc(q.adjustment)}。調査基準日 ${esc(data.report.asOf)}。日次更新で、リアルタイムではありません。</small><h4>前回からの変化</h4><ul>${c.changes.map(x=>'<li>'+esc(x)+'</li>').join('')}</ul>${c.alerts.length?'<div class="auto-alert"><strong>新しい開示：従来の仮説を再確認</strong>'+c.alerts.map(a=>'<p>'+link(a.url,a.date+' '+a.title)+'</p>').join('')+'</div>':''}<h4>根拠と反対材料</h4><p>${esc(m.thesis)}</p><p><strong>反証：</strong>${esc(m.counter)}</p><details><summary>利益・価格の分析案</summary><p>${esc(m.profit)}</p><p>${esc(m.valuation)}</p>${s?'<p>分析上の仮定 · '+esc(s.asOf)+' ／ '+esc(s.basis)+'</p><div class="scroll"><table><thead><tr><th>場合</th><th>EPS</th><th>PER</th><th>仮定株価</th><th>今の終値から</th></tr></thead><tbody>'+s.cases.map((x,i)=>'<tr><td>'+['弱気','基本','強気'][i]+'</td><td>'+num(x.eps)+'</td><td>'+num(x.per)+'</td><td>'+num(x.eps*x.per)+'円</td><td>'+(finite(q.price)&&q.price>0?num((x.eps*x.per/q.price-1)*100)+'%':'未確認')+'</td></tr>').join('')+'</tbody></table></div><p>'+s.cases.map((x,i)=>esc(['弱気','基本','強気'][i]+'：'+x.basis)).join('<br>')+'</p>':'<p>根拠のそろった3シナリオはまだありません。こちらの追加調査項目です。</p>'}${!c.scenarioUsable?'<p>購入上限・投入額の計算は保留です。未完成の分析、古い資料、新開示、価格未確認を自動で通過させません。</p>':''}</details><h4>こちらで追加調査すること</h4><p>${esc(c.todo)}</p><details><summary>未解決事項・見直し条件</summary><p>${esc(m.unknown)}</p><p>${esc(m.exit)}</p></details><p class="sizing">${amount?'あなたの条件での購入上限参考 '+num(amount.entry)+'円 ／ 現物投入額上限 '+num(amount.limit)+'円。弱気価格を下回る損失・費用・売買単位は別途確認。':'投資額は未算定。分析がそろい、個人条件を設定した時点で自動計算します。'}</p><div class="action-grid decision-actions">${['購入を検討','待つ','見送る'].map(label=>`<button type="button" data-auto-code="${esc(c.code)}" data-choice="${label}">${label}</button>`).join('')}</div><p class="decision-last">${last?'あなたの判断：'+esc(last.choice)+'（'+esc(last.at.slice(0,10))+'）':'判断は未記録です。ボタンは意思の記録で、注文は出しません。'}</p></article>`;}).join(''):'<p>自動調査を取得できません。保存済みの手動分析は下の詳細欄で確認できます。</p>';
 const watch=document.querySelector('#personalWatch');if(watch)watch.innerHTML=personal.holdings.length?personal.holdings.map(h=>{const ds=(data?.feed?.items||[]).filter(x=>x.code===h.code);return '<details><summary>'+esc(h.code+' '+h.name)+' · 収集範囲内 '+ds.length+'件</summary>'+ds.slice(0,10).map(d=>'<p>'+link(d.url,d.published+' '+d.title)+'</p>').join('')+'<p>公開開示と端末内で照合。保有情報を公開・送信していません。</p></details>';}).join(''):'<p>保有一覧を読み込むと、この端末で新規開示を自動照合します。調査担当へ保有情報は送信されません。</p>';
 }
 function render(payload){data=payload;const a=data?.report?.autopilot;home.innerHTML=`<div class="eyebrow">投資調査 · 自動更新</div><h1>今回の結論と、変わったところ。</h1><p>普段はここを確認するだけ。数値や資料の入力は不要です。購入・売却はご自身で決めます。</p><p id="autoStatus" role="status">${a?esc('更新 '+a.updatedAt+' ／ '+a.cards.length+'社 ／ '+data.report.status):'自動調査データを取得できません。再読み込みしてください。'}</p>${a&&Date.now()-Date.parse(a.updatedAt)>3*86400000?'<p class="auto-alert">更新から3日以上経っています。最新の判断として使う前に更新状況を確認してください。</p>':''}<p class="muted">月〜土曜7時：開示・終値・変更点を更新。土曜：候補精査と反証。実行PCとCodexの起動が必要です。現在の初期メモは精査未完を含みます。</p><details id="personalSettings"><summary>あなたの条件（最初と変更時だけ）</summary><p>端末内に自動保存します。数値を推測して埋めません。未設定でも調査結果は閲覧できます。</p><div class="fields">${[['cash','今回使える現金（円）'],['lossBudget','1銘柄の許容損失額（円）'],['assets','金融資産総額（円）'],['maxWeight','1銘柄の上限比率（%）'],['returnRequired','基本価格に求める上昇率（%）']].map(([k,t])=>`<label>${t}<input data-personal="${k}" type="number" min="0" step="any" value="${esc(personal[k]??'')}"></label>`).join('')}</div><p id="personalSaved" role="status">${esc(saveError||'入力変更時に自動保存します。端末間の自動同期はありません。')}</p><div class="action-grid"><button id="personalExport">個人設定・判断をバックアップ</button><button id="personalImport">個人設定・判断を復元</button><button id="holdingsImport">保有一覧JSONを読み込む</button></div><input type="file" id="personalFile" accept="application/json,.json" hidden><input type="file" id="holdingsFile" accept="application/json,.json" hidden><p>以前共有した holdings / stocks 形式のJSONを読み込めます。照合に使うコード・会社名だけを保持します。</p><div id="personalWatch"></div></details><div id="autoCards"></div><details id="autoHistory"><summary>過去の調査・判断を確認する（自動記録）</summary>${(a?.history||[]).slice().reverse().map(h=>'<details><summary>'+esc(h.at)+' · '+h.snapshot.cards.length+'社</summary>'+h.snapshot.cards.map(c=>'<h4>'+esc(c.code+' '+c.memo.name)+'</h4><p>'+esc(c.memo.verdict)+'</p><p>当時の終値 '+num(c.quote.price)+'円（'+esc(c.quote.date)+'）</p><p>'+esc(c.memo.thesis)+'</p><p>反証：'+esc(c.memo.counter)+'</p><details><summary>当時の利益・価格・未解決事項</summary><p>'+esc(c.memo.profit)+'</p><p>'+esc(c.memo.valuation)+'</p><p>'+esc(c.memo.gap)+'</p><p>'+esc(c.memo.catalyst)+'</p><p>'+esc(c.memo.unknown)+'</p><p>'+esc(c.memo.exit)+'</p></details>').join('')+'</details>').join('')}<details><summary>あなたの判断履歴</summary><div id="personalHistory"></div></details></details><p id="manualAutosave" role="status"></p>`;cards();history();
 home.oninput=e=>{const k=e.target.dataset.personal;if(!k)return;personal[k]=e.target.value===''?null:Number(e.target.value);save();cards();};
 home.onclick=e=>{const code=e.target.dataset.autoCode,choice=e.target.dataset.choice;if(!code)return;if(personal.decisions.length>=500){document.querySelector('#personalSaved').textContent='判断記録が500件に達しました。バックアップしてください。';document.querySelector('#personalSettings').open=true;return;}const card=data.report.autopilot.cards.find(x=>x.code===code);personal.decisions.push({code,choice,at:new Date().toISOString(),researchAsOf:data.report.asOf,snapshot:JSON.parse(JSON.stringify(card))});if(!save()){personal.decisions.pop();document.querySelector('#personalSettings').open=true;}cards();history();};
 document.querySelector('#personalExport').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(personal,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='research-personal.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
 document.querySelector('#personalImport').onclick=()=>document.querySelector('#personalFile').click();document.querySelector('#holdingsImport').onclick=()=>document.querySelector('#holdingsFile').click();
 for(const id of ['personalFile','holdingsFile'])document.querySelector('#'+id).onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>5000000)throw Error('5MB以下にしてください');const d=JSON.parse(await f.text());let next;if(id==='personalFile'){if(!validPersonal(d))throw Error('形式が一致しません');if(!confirm('この端末の個人設定と判断履歴をバックアップで置き換えますか？'))return;next=d;}else{const rows=d.holdings||d.stocks;if(!Array.isArray(rows)||rows.length>100||!rows.every(x=>/^[0-9A-Z]{4}$/.test(String(x.code))&&typeof x.name==='string'))throw Error('コードと会社名の一覧を確認してください');next={...personal,holdings:[...new Map(rows.map(h=>[String(h.code),{code:String(h.code),name:h.name}])).values()]};}const prev=personal;personal=next;if(!save())personal=prev;render(data);document.querySelector('#personalSettings').open=true;}catch(err){document.querySelector('#personalSaved').textContent='読込失敗：'+err.message;}finally{e.target.value='';}};
 }
 function history(){const el=document.querySelector('#personalHistory');if(el)el.innerHTML=personal.decisions.slice().reverse().map(d=>'<p>'+esc(d.at+' '+d.code+' '+d.choice)+' ／ 調査基準 '+esc(d.researchAsOf)+'</p>').join('')||'<p>まだ判断は記録していません。</p>';}
 let timer;function autosave(){clearTimeout(timer);timer=setTimeout(()=>{if(isDemo)return;const msg=document.querySelector('#manualAutosave');try{if(!records.every(validRecord)){if(msg)msg.textContent='手動欄に不正な値があります。自動保存を保留しています。';return;}localStorage.setItem(key,JSON.stringify({schema:1,records}));if(msg)msg.textContent='詳細欄の変更もこの端末に自動保存しました。';}catch{if(msg)msg.textContent='詳細欄を保存できません。書き出して保管してください。';}},250);}
 ['input','change','click'].forEach(type=>advanced.addEventListener(type,autosave));window.addEventListener('pagehide',()=>{if(!isDemo&&records.every(validRecord))try{localStorage.setItem(key,JSON.stringify({schema:1,records}));}catch{}});
 window.addEventListener('research-feed-ready',e=>render(e.detail));if(window.RRPublicFeed)render(window.RRPublicFeed);else render(null);
 async function refreshPublic(){if(document.hidden||home.contains(document.activeElement)&&document.activeElement.matches('input'))return;try{const get=async name=>{const r=await fetch('../data/'+name+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error();return r.json();};const [report,feed]=await Promise.all([get('research-weekly.json'),get('research-disclosures.json')]);if(!Array.isArray(report.autopilot?.cards)||!Array.isArray(feed.items))throw Error();if(report.autopilot.updatedAt!==data?.report?.autopilot?.updatedAt){render({report,feed});}}catch{const s=document.querySelector('#autoStatus');if(s)s.textContent='再取得に失敗しました。前回取得分を表示しています。';}}
 setInterval(refreshPublic,300000);window.addEventListener('online',refreshPublic);
 window.RRAuto={sizing,validPersonal,saveManual:autosave,refreshPublic};
})();
