'use strict';
// Public evidence inbox is deliberately separate from private/local assessments.
(async function(){
 const box=document.createElement('section');box.id='researchFeed';document.querySelector('main').prepend(box);
 box.innerHTML='<h2>新しい開示・週次調査</h2><p role="status">公開調査フィードを読み込み中…</p>';
 const safe=u=>{try{const x=new URL(u);return x.protocol==='https:'?x.href:'';}catch{return '';}};
 const link=(u,t)=>safe(u)?`<a href="${esc(safe(u))}" target="_blank" rel="noopener noreferrer">${esc(t)}</a>`:esc(t);
 const get=async file=>{const r=await fetch('../data/'+file+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json();};
 const [feedResult,reportResult]=await Promise.allSettled([get('research-disclosures.json'),get('research-weekly.json')]);
 let feed=null,report=null;
 if(feedResult.status==='fulfilled'&&feedResult.value.schema===1&&Array.isArray(feedResult.value.items))feed=feedResult.value;
 if(reportResult.status==='fulfilled'&&reportResult.value.schema===1&&Array.isArray(reportResult.value.memos))report=reportResult.value;
 const stale=feed&&(!Number.isFinite(Date.parse(feed.attemptedAt))||Date.now()-Date.parse(feed.attemptedAt)>3*86400000);
 box.innerHTML=`<h2>新しい開示・週次調査</h2><p>開示の入口 → 本文確認 → 反証 → 価格・購入条件の確認。個人の評価や保有額は自動で書き換えません。</p><p id="feedStatus" role="status">${feed?esc('取得 '+feed.attemptedAt+' ／ 対象 '+feed.windowStart+'〜'+feed.windowEnd+' ／ '+(feed.status==='ok'?'対象日の全ページ取得済み':'一部取得失敗・収集範囲に欠落あり')+(stale?' ／ 更新から3日超：鮮度を確認してください':'')):'開示フィードを取得できません。未取得を「該当なし」とは扱いません。'}</p><p class="muted">${esc(feed?.scope||'TDnet公開一覧の収集状態は不明です。')} 株価・買い条件の自動更新ではありません。</p><details><summary>日別の収集範囲</summary>${(feed?.coverage||[]).map(c=>'<p>'+link(c.source,c.date)+' · '+esc(c.status==='ok'?c.rows+'件を確認':'取得失敗 '+c.reason)+'</p>').join('')}</details><div id="weeklyFeed"></div><details open><summary>新規開示の入口（本文未精査を含む）</summary><label>コード・会社名・見出しで絞る<input id="feedQuery" placeholder="例：上方修正、自己株式、9509"></label><label><input id="feedSignals" type="checkbox" checked> 変化の手掛かりがある開示に絞る</label><p id="feedCount"></p><div id="feedItems"></div><button id="feedMore" type="button">さらに50件表示</button></details><p id="feedAction" role="status"></p>`;
 const weekly=box.querySelector('#weeklyFeed');
 const fields={thesis:'投資仮説',gap:'評価のずれ',profit:'利益の計算',valuation:'価格評価',catalyst:'きっかけ',counter:'反証',unknown:'未確認事項',exit:'再検討・撤退条件'};
 weekly.innerHTML=report?`<h3>調査メモ · ${esc(report.asOf)} ／ ${esc(report.status)}</h3><p>${esc(report.scope)}</p>${Date.now()-Date.parse(report.asOf+'T23:59:59+09:00')>8*86400000?'<p>調査基準日から8日超です。最新調査として扱わないでください。</p>':''}${report.memos.map(m=>`<details><summary>${esc(m.code+' '+m.name+' · '+m.verdict)}</summary><p>${esc(m.depth)}</p>${Object.entries(fields).map(([k,label])=>'<h4>'+label+'</h4><p style="white-space:pre-wrap;overflow-wrap:anywhere">'+esc(m[k]||'未確認')+'</p>').join('')}<p>${(m.sources||[]).map(s=>link(s.url,s.published+' '+s.title)).join('<br>')}</p><button type="button" data-memo="${esc(m.code)}">このメモを調査記録へ追加</button></details>`).join('')}`:'<h3>週次調査</h3><p>調査結果を取得できません。確認済みメモとして扱いません。</p>';
 let limit=50;
 function draw(){const query=box.querySelector('#feedQuery').value.trim().toLowerCase(),signals=box.querySelector('#feedSignals').checked;const rows=(feed?.items||[]).filter(x=>(!signals||x.tags?.length)&&(!query||(x.code+' '+x.name+' '+x.title).toLowerCase().includes(query)));box.querySelector('#feedCount').textContent=rows.length+'件（最大'+limit+'件を表示）。見出しの分類は上方・下方の判定や推奨順位ではありません。';box.querySelector('#feedItems').innerHTML=rows.slice(0,limit).map(x=>`<article style="border-top:1px solid var(--line);padding:12px 0;overflow-wrap:anywhere"><small>${esc(x.published+' '+x.time+' ／ '+x.code+' '+x.name)}</small><p>${link(x.url,x.title)}</p><small>${esc(x.tags.join('・')||'分類なし')} ／ ${esc(x.status)}</small><p><button type="button" data-lead="${esc(x.id)}">調査候補へ追加</button></p></article>`).join('')||'<p>表示条件に合う開示がありません。購入適格銘柄の判定ではありません。</p>';box.querySelector('#feedMore').hidden=rows.length<=limit;}
 box.querySelector('#feedQuery').oninput=()=>{limit=50;draw();};box.querySelector('#feedSignals').onchange=()=>{limit=50;draw();};box.querySelector('#feedMore').onclick=()=>{limit+=50;draw();};draw();
 box.addEventListener('click',e=>{const lead=e.target.dataset.lead,memo=e.target.dataset.memo;if(!lead&&!memo)return;const msg=box.querySelector('#feedAction');if(isDemo){msg.textContent='架空例から実在銘柄の画面に戻ってください。';return;}const x=lead?feed.items.find(x=>x.id===lead):report.memos.find(x=>x.code===memo);if(!x||!(/^[0-9A-Z]{4}$/.test(x.code)))return;let i=records.findIndex(r=>r.code===x.code);if(i<0){if(records.length>=100){msg.textContent='候補は最大100社です。';return;}records.push(RRWorkflowAttach(RRDecisionAttach(M.blank(x.code,x.name))));i=records.length-1;}const r=records[i],w=r.workflow,source=lead?x.url:(x.sources||[]).map(s=>s.url).join('\n'),actual=lead?x.title:Object.entries(fields).map(([k,v])=>v+'：'+(x[k]||'未確認')).join('\n');if(w.followups.some(f=>f.source===source&&f.actual===actual)){msg.textContent='この内容は既に追加済みです。';return;}if(w.followups.length>=100){msg.textContent='継続記録の上限100件です。';return;}w.followups.push({date:lead?x.published:report.asOf,kind:'公開調査の受信',before:'既存評価を維持',actual,action:'一次資料・最新株価を確認して手動で再評価',source});w.checks.forEach(c=>{c.state='pending';delete c.basis;});w.reviewOutcome='未解決あり';selected=i;render();msg.textContent='継続記録に追加しました。既存の評価は保持し、購入チェックは新情報の再確認待ちに戻しました。新情報との整合を確認し「現在の評価を記録」で保存してください。';document.querySelector('#detailTitle')?.scrollIntoView({behavior:'smooth'});});
})().catch(()=>{const box=document.querySelector('#researchFeed');if(box)box.textContent='公開調査を表示できません。既存の手動調査記録はそのまま利用できます。';});
