(function(root){
 'use strict';const W=root.RRWorkflowModel,$=id=>document.getElementById(id),f=x=>typeof x==='number'&&Number.isFinite(x)?x.toLocaleString('ja-JP',{maximumFractionDigits:2}):'未設定';
 function render(r,esc,onChange){const w=r.workflow;
 const input=(key,label,number=false)=>`<label>${label}${number?`<input type="number" step="any" data-w="${key}" value="${esc(w[key]??'')}">`:`<textarea data-w="${key}">${esc(w[key])}</textarea>`}</label>`;
 $('workflow').innerHTML=`<section><h2>候補 → 精査・反証 → 条件確認 → 継続検証</h2><p>ご提示の運用案を取り入れた個人用の工程です。Kaihouの独自モデルを再現したものではありません。新規開示・週次調査は上の公開フィードに表示します。全市場の精査が完了したことを意味しません。</p><p id="workflowStatus" role="status"></p><div id="candidateBoard" class="scroll"></div><details><summary>候補を手動で追加</summary><div class="fields"><label>コード<input id="newCode" maxlength="10"></label><label>会社名<input id="newName" maxlength="100"></label><button type="button" id="addCandidate">未評価の候補を追加</button></div></details>
 <div class="fields"><label>探す型<select data-w="type">${W.types.map(v=>`<option ${v===w.type?'selected':''}>${esc(v)}</option>`).join('')}</select></label><label>管理状態（手動・発注ではありません）<select data-w="stage">${W.stages.map(v=>`<option ${v===w.stage?'selected':''}>${esc(v)}</option>`).join('')}</select></label></div>${input('selectedReason','抽出・除外の理由')}</section>
 <section><h2>共通8項目の投資メモ</h2><p>仮説・評価のずれ・価格シナリオ・最大の反論は下の既存分析欄と共有します。</p><div class="grid">${input('profitLogic','③ 利益への道筋（数量・単価・費用・株数）')}${input('catalyst','⑤ きっかけ・公表予定・確認先')}${input('indicator','⑤ 途中で確認する指標')}${input('unknown','⑦ 未確認・矛盾・確認先')}${input('exitRule','⑧ 再検討・撤退条件（数字・出来事・期限）')}${input('verdict','判断理由：購入検討／監視／見送り／該当なし')}</div><div class="fields">${input('catalystMonths','きっかけの成立まで（月・未確認は空欄）',true)}</div><p>基本の評価期間は上の設定を維持。購入検討の工程では24か月以内でも現在の評価期間を超える材料は保留します。時間軸を変える場合は理由を履歴に残してください。</p>
 <details><summary>重要数値台帳：事実と推計の対象期を分ける</summary><p>確認済みは過去の照合記録で、現在の最新性を保証しません。数値の編集で照合状態は解除されます。</p><div id="factRows"></div><button id="addFact" type="button">数値行を追加</button></details>
 <details><summary>将来利益を計算する（未入力をゼロにしません）</summary><p>全社の簡易計算。部門別積み上げは上の利益メモに記載し、二重計上を点検します。金額は億円、株数は万株。分析仮定の計算結果は会社予想と別です。</p><div class="fields">${[['sales','売上（億円）'],['margin','営業利益率（%）'],['nonOperating','営業外損益（億円）'],['exceptional','特別損益（億円）'],['tax','実効税率（%）'],['minority','非支配利益（億円）'],['shares','希薄化後株数（万株）']].map(([k,l])=>`<label>${l}<input type="number" step="any" data-bridge="${k}" value="${esc(w.bridge[k]??'')}"></label>`).join('')}</div>${['period','basis'].map((k,i)=>`<label>${['対象期','各入力の根拠・出典・仮定'][i]}<textarea data-bridge="${k}">${esc(w.bridge[k])}</textarea></label>`).join('')}<p id="bridgeResult"></p><p>営業利益＝売上×利益率。親会社利益＝（営業利益＋営業外＋特別）×（1−税率）−非支配利益。EPS＝親会社利益÷株数。税効果や赤字の特殊事情には別モデルが必要です。シナリオへ自動転記しません。</p></details></section>
 <section><h2>独立した反証工程</h2><p>既存仮説を支持する探索と切り分けた記録です。別AIの賛同や記事の件数を証拠にしません。</p><div class="fields"><label>確認日<input type="date" data-w="reviewDate" value="${esc(w.reviewDate)}"></label><label>結論<select data-w="reviewOutcome">${['未実施','未解決あり','確認済み'].map(v=>`<option ${v===w.reviewOutcome?'selected':''}>${v}</option>`).join('')}</select></label></div><div class="grid">${input('reviewSource','反証に使った資料・公表日・対象期間')}${input('reviewFindings','否定材料・答えられたこと・残る疑問')}</div><details><summary>次回も使う反証指示文</summary><pre class="snapshot">${esc(root.RRRedTeamPrompt)}</pre></details></section>
 <section><h2>購入検討チェック（自動売買ではありません）</h2><p>条件がそろわなければ「該当なし」が正常です。各項目の根拠と日付を記入し、現在の入力で確認します。価格・利益仮定・資料・損失条件が変わると再確認が必要です。</p>
 <div class="fields">${input('returnRequired','基本価格に求める値上がり率（%）',true)}${input('lossBudget','1銘柄の許容損失額（円）',true)}${input('maxWeight','金融資産に対する1銘柄上限（%）',true)}${input('cash','今回使える現金（円）',true)}${input('planned','検討する投入額（円）',true)}</div><p id="entryResult"></p><p id="sizeResult"></p><p class="muted">購入上限の参考値＝基本ケース株価÷（1＋要求値上がり率）。投入額上限＝許容損失÷弱気下落率、金融資産×銘柄上限、現金の最小値。弱気価格は下値保証ではなく、想定損失超過はあり得ます。信用・売買単位・費用は未反映。金融資産総額は下の保有全体欄に入力します。</p>
 <div class="grid">${w.checks.map((c,i)=>`<div class="item"><strong>${i+1}. ${esc(c.label)}</strong><p id="purchaseGate${i}"></p><label>根拠・未解決事項<textarea data-pcheck="${i}:note">${esc(c.note)}</textarea></label><label>確認日<input type="date" data-pcheck="${i}:date" value="${esc(c.date)}"></label><button type="button" data-confirm="${i}">現在の入力で確認</button><button type="button" data-unconfirm="${i}">保留に戻す</button></div>`).join('')}</div><p id="purchaseResult" role="status"></p></section>
 <section><h2>保有・監視・見送り後の検証記録</h2><p>見送りも記録対象。株価変動と仮説の変化を区別し、当時の判断を上書きしません。</p><div class="fields"><label>確認日<input id="followDate" type="date"></label><label>変化の種類<select id="followKind"><option>決算・利益予想</option><option>きっかけの変化</option><option>資本政策</option><option>相場変動</option><option>分析訂正</option><option>月次振り返り</option></select></label></div><div class="grid">${[['followBefore','前回の仮説・予想'],['followActual','今回の事実と予想との差'],['followAction','継続／再検討／見送り等の理由'],['followSource','出典・公表日・対象期間']].map(([id,l])=>`<label>${l}<textarea id="${id}"></textarea></label>`).join('')}</div><button type="button" id="addFollow">検証記録を追加（保存は下の記録ボタン）</button><div id="followList"></div></section>`;
 function facts(){ $('factRows').innerHTML=w.facts.map((a,i)=>`<div class="item"><div class="fields">${[['name','項目'],['value','値'],['unit','単位'],['period','対象期間'],['published','公表日'],['source','出典URL']].map(([k,l])=>`<label>${l}<input type="${k==='value'?'number':k==='published'?'date':'text'}" step="any" data-fact="${i}:${k}" value="${esc(a[k]??'')}"></label>`).join('')}<label>区分<select data-fact="${i}:kind">${['一次資料','二次資料','分析仮定'].map(v=>`<option ${v===a.kind?'selected':''}>${v}</option>`).join('')}</select></label><label><input type="checkbox" style="width:auto" data-fact="${i}:checked" ${a.checked?'checked':''}>資料と照合済み</label></div></div>`).join(''); }
 facts();
 $('workflow').oninput=e=>{const t=e.target;const value=t.type==='number'?(t.value===''?null:Number(t.value)):t.value;if(t.dataset.w)w[t.dataset.w]=value;if(t.dataset.bridge)w.bridge[t.dataset.bridge]=value;if(t.dataset.pcheck){const[i,k]=t.dataset.pcheck.split(':');w.checks[i][k]=value;}if(t.dataset.fact){const[i,k]=t.dataset.fact.split(':');w.facts[i][k]=k==='checked'?t.checked:value;if(k!=='checked'){w.facts[i].checked=false;document.querySelector(`[data-fact="${i}:checked"]`).checked=false;}}onChange();};
 $('workflow').onclick=e=>{if(e.target.dataset.confirm!==undefined){const c=w.checks[Number(e.target.dataset.confirm)];c.state='pass';c.basis=W.basis(r);onChange();}if(e.target.dataset.unconfirm!==undefined){w.checks[Number(e.target.dataset.unconfirm)].state='pending';onChange();}};
 $('addFact').onclick=()=>{if(w.facts.length>=100)return;w.facts.push({name:'',value:null,unit:'',period:'',published:'',source:'',kind:'一次資料',checked:false});facts();onChange();};
 $('addFollow').onclick=()=>{const entry={date:$('followDate').value,kind:$('followKind').value,before:$('followBefore').value,actual:$('followActual').value,action:$('followAction').value,source:$('followSource').value};if(!Object.values(entry).every(x=>x.trim())){$('status').textContent='検証記録の各欄を入力してください。';return;}if(w.followups.length>=100){$('status').textContent='検証記録は100件までです。書き出して保管してください。';return;}w.followups.push(entry);['followBefore','followActual','followAction','followSource'].forEach(id=>$(id).value='');$('status').textContent='検証記録を追加しました。下の記録ボタンで保存します。';onChange();};
 }
 function refresh(records,r,esc){if(!$('candidateBoard'))return;const w=r.workflow,x=W.calculations(r),g=W.gates(r),count=records.filter(a=>a.workflow&&W.ready(a)).length;
 $('workflowStatus').textContent=count?`入力された条件の充足 ${count}社。売買の適否や資料の真偽を保証するものではありません。`:'現在、購入検討の入力条件を満たす銘柄は該当なし。';
 $('candidateBoard').innerHTML='<table><thead><tr><th>銘柄</th><th>型</th><th>管理状態</th><th>工程の結果</th></tr></thead><tbody>'+records.map(a=>`<tr><td>${esc(a.name)}${a.workflow?.pilot?'（試行）':''}</td><td>${esc(a.workflow?.type||'未分類')}</td><td>${esc(a.workflow?.stage||'候補')}</td><td>${a.workflow&&W.ready(a)?'入力条件が充足':'未達・監視対象'}</td></tr>`).join('')+'</tbody></table>';
 const b=W.bridge(w.bridge);$('bridgeResult').textContent=b?`分析仮定の計算：営業利益 ${f(b.op)}億円 ／ 親会社利益 ${f(b.net)}億円 ／ EPS ${f(b.eps)}円。${w.bridge.period&&w.bridge.basis?'':'対象期・根拠が未記入。'}`:'利益計算は未設定。ゼロも明示入力してください。';
 $('entryResult').textContent=`基本ケースからの購入上限参考値：${f(x.ceiling)}円。${x.ceiling!==null&&r.price>x.ceiling?'現在の基準株価は上限を超えています。':''} ${x.scenario?'':'3ケースの利益・倍率・成立時期・根拠は未完または不整合。'}`;
 $('sizeResult').textContent=`弱気下落率：${f(x.down===null?null:x.down*100)}% ／ 投入額上限の試算：${f(x.amount)}円。未設定は無制限を意味しません。`;
 w.checks.forEach((c,i)=>$('purchaseGate'+i).textContent=g[i]?'記録上の条件を充足':c.state==='pass'&&c.basis!==W.basis(r)?'入力変更あり：再確認が必要':'未達・保留（根拠／日付／関連入力を確認）');
 $('purchaseResult').textContent=g.every(Boolean)?'入力条件がそろいました。最終判断は人が資料・価格・資金を確認して行います。':'購入検討は保留：未達 '+g.map((v,i)=>v?null:i+1).filter(Boolean).join('・')+'。該当なしとして記録できます。';
 $('followList').innerHTML=w.followups.slice().reverse().map(e=>`<details><summary>${esc(e.date)} · ${esc(e.kind)}</summary><p>前回：${esc(e.before)}</p><p>今回：${esc(e.actual)}</p><p>判断：${esc(e.action)}</p><p>出典：${esc(e.source)}</p></details>`).join('')||'<p class="muted">新しい検証記録はまだありません。</p>';
 }
 root.RRWorkflowUI={render,refresh};
 root.RRRedTeamPrompt='この銘柄の投資仮説を支持する探索とは切り分けて、誤りの可能性を調べてください。需要の一時性、利益の一過性、資金繰り、希薄化、競争、会社計画の未達履歴、現在価格の期待を確認します。重要な主張ごとに出典・公表日・対象期間を付け、事実と解釈を分離してください。同じ会社説明の転載を独立証拠に数えず、AI同士の一致を根拠にしないでください。最も強い反論、まだ答えられない点、判断を変える次の情報を示してください。資料がなければ不明とし、買い結論を強制しないでください。';
})(window);
