(function(root){
 'use strict';
 const configs={
 '3891':{type:1,eps:398.23,op:60,published:'2026-07-31',period:'2027年3月期・会社通期予想',source:'https://finance-frontend-pc-dist.west.edge.storage-yahoo.jp/disclosure/20260731/20260729501753.pdf',profit:'数量×単価・製品構成→売上→原料費・固定費→営業利益→税・株数→EPS。前回会社計画営業60億に対し市場参考68億で、単なる会社超過は優位性の証明にならない。将来純利益への積み上げは未完。',catalyst:'次回決算で高付加価値品の数量・採算と設備余力を確認。予定日と実現月数は未確認。',indicator:'四半期単独利益率、製品別稼働、売掛金・在庫、営業CF',exit:'成長が止まり利益率低下と在庫・債権増が重なる場合に仮説を再検討。数値閾値と期限は購入検討前に固定する。'},
 '4401':{type:2,eps:329.98,op:500,published:'2026-08-07',period:'2027年3月期・会社通期予想',source:'https://www.adeka.co.jp/ir/library/pdf/260807ke.pdf',profit:'部門別売上×各利益率を積み上げ、全社費用・税・非支配利益・株数を反映。半導体部門の伸びが他部門の減速を超えて全社EPSへ届くかを検証。半導体計画100億／全社500億という前回資料だけで「隠れた」と断定しない。',catalyst:'次回決算の部門別利益・下期計画。2028年設備は現在の12か月評価へ加算しない。',indicator:'半導体材料の数量・構成、他部門利益、全社EPSの改定',exit:'他部門や円高で半導体増益が相殺される場合。隠れた成長の未織込みを立証できない場合は監視継続または見送り。'},
 '1941':{type:3,eps:372.12,op:270,published:'2026-07-31',period:'2027年3月期・会社通期予想',source:'https://www.chudenko.co.jp/info/library/images/tanshin27_31.pdf',profit:'受注残×期間内の売上化→工事粗利→人件費・外注費→利益。資産売却益を恒常利益に混ぜず、自己株取得は実際の株数減少でEPSへ反映する。',catalyst:'還元・保有資産縮小の実行、および次回決算の工事採算。方針と実行時期を区別し、具体的な期限を確認する。',indicator:'取得済み自己株額・株数、資産売却と資金使途、工事粗利率',exit:'還元の実行が遅れる、工事採算が悪化する、資産の換金・還元が評価期間に間に合わない場合に再検討。'}
 };
 root.RRWorkflowAttach=r=>{if(r.workflow)return r;const w=root.RRWorkflowModel.blank(),c=configs[r.code];if(c){Object.assign(w,{pilot:true,type:root.RRWorkflowModel.types[c.type],stage:'監視',selectedReason:'3つの型の工程を試すための試行対象。推奨順位・買い推奨ではない。9/26までの既存調査を利用。',profitLogic:c.profit,catalyst:c.catalyst,indicator:c.indicator,exitRule:c.exit,unknown:r.decision?.next||'',reviewDate:'2026-09-26',reviewOutcome:'未解決あり',reviewSource:c.source,reviewFindings:(r.decision?.counter||'')+'\n既存資料に基づく反証整理は実施。将来EPS・倍率、期限、許容損失が未確定で反論を解消したとはいえない。',verdict:'監視：工程を一巡した結果、購入検討の条件は未達。将来EPS/PER・期限・損失予算が埋まるまで該当なし。'});w.facts=[{name:'会社予想EPS',value:c.eps,unit:'円/株',period:c.period,published:c.published,source:c.source,kind:'一次資料',checked:true},{name:'会社予想営業利益',value:c.op,unit:'億円',period:c.period,published:c.published,source:c.source,kind:'一次資料',checked:true},{name:'独自の将来EPS（未推計）',value:null,unit:'円/株',period:'評価期間内・対象期未設定',published:'',source:'',kind:'分析仮定',checked:false}];}else if(r.code==='4971'){w.type=root.RRWorkflowModel.types[1];w.selectedReason='既存調査を保持。今回の3社試行の対象外で、劣後と判断したわけではない。';}r.workflow=w;return r;};
})(typeof window==='undefined'?globalThis:window);
